# Feature Engineering

## Objective

The objective of this notebook is to transform the cleaned telecom dataset into a machine learning ready dataset.

Tasks performed:

- Loading cleaned dataset
- Dropping unnecessary columns
- Separating target variable
- One-Hot Encoding
- Label Encoding (if required)
- Feature Scaling using StandardScaler
- Feature Selection
- Saving processed dataset

In [60]:
# =====================================================
# Import Required Libraries
# =====================================================

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

print("Libraries imported successfully.")

Libraries imported successfully.

In [61]:
# =====================================================
# Load Cleaned Dataset
# =====================================================

df = pd.read_csv("../data/processed/cleaned_telco_data.csv")

print("Dataset Loaded Successfully")
print()

df.head()

Dataset Loaded Successfully

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,...,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,California,...,20,0.00,59.65,3,Churned,Yes,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,California,...,0,390.80,1024.10,3,Churned,Yes,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,California,...,0,203.94,1910.88,2,Churned,Yes,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,California,...,0,494.00,2995.07,2,Churned,Yes,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,California,...,0,234.21,3102.36,2,Churned,Yes,67,2793,Price,Extra data charges

In [62]:
# =====================================================
# Dataset Shape and Columns
# =====================================================

print("Dataset Shape :", df.shape)

print("\nTarget Variable")

print(df["Churn Label"].value_counts())

Dataset Shape : (7043, 50)

Target Variable
Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

## Removing Unnecessary Columns

Some columns contain identifiers or information that should not be used during model training because they do not contribute to prediction or may cause data leakage.

In [63]:
# =====================================================
# Remove Identifier and Target Leakage Columns
# =====================================================

drop_columns = [

    "Customer ID",
    "Country",
    "State",
    "City",
    "Zip Code",
    "Latitude",
    "Longitude",

    "Customer Status",
    "Churn Category",
    "Churn Reason",
    "Churn Score"

]

df = df.drop(columns=drop_columns)

print("Columns Removed Successfully")

print("Dataset Shape :", df.shape)

df.head()

Columns Removed Successfully
Dataset Shape : (7043, 39)

,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Population,Quarter,Referred a Friend,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Churn Label,CLTV
0,Male,78,No,Yes,No,No,0,68701,Q3,No,...,Bank Withdrawal,39.65,39.65,0.00,20,0.00,59.65,3,Yes,5433
1,Female,74,No,Yes,Yes,Yes,1,55668,Q3,Yes,...,Credit Card,80.65,633.30,0.00,0,390.80,1024.10,3,Yes,5302
2,Male,71,No,Yes,No,Yes,3,47534,Q3,No,...,Bank Withdrawal,95.45,1752.55,45.61,0,203.94,1910.88,2,Yes,3179
3,Female,78,No,Yes,Yes,Yes,1,27778,Q3,Yes,...,Bank Withdrawal,98.50,2514.50,13.43,0,494.00,2995.07,2,Yes,5337
4,Female,80,No,Yes,Yes,Yes,1,26265,Q3,Yes,...,Bank Withdrawal,76.50,2868.15,0.00,0,234.21,3102.36,2,Yes,2793

## Separating Features and Target Variable

In [64]:
# =====================================================
# Separate Features and Target
# =====================================================

X = df.drop("Churn Label", axis=1)

y = df["Churn Label"]

print("Feature Matrix Shape :", X.shape)
print("Target Shape :", y.shape)

Feature Matrix Shape : (7043, 38)
Target Shape : (7043,)

## One-Hot Encoding

Categorical variables are converted into numerical format using One-Hot Encoding so that machine learning algorithms can process them.

In [65]:
# =====================================================
# One-Hot Encoding
# =====================================================

categorical_columns = X.select_dtypes(include="object").columns

print("Categorical Columns")

print(categorical_columns)

Categorical Columns
Index(['Gender', 'Under 30', 'Senior Citizen', 'Married', 'Dependents',
       'Quarter', 'Referred a Friend', 'Offer', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Internet Type',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method'],
      dtype='object')

In [66]:
# =====================================================
# Apply One-Hot Encoding
# =====================================================

X = pd.get_dummies(
    X,
    columns=categorical_columns,
    drop_first=True
)

print("One-Hot Encoding Completed")
print()

print("New Feature Shape :", X.shape)

X.head()

One-Hot Encoding Completed

New Feature Shape : (7043, 43)

,Age,Number of Dependents,Population,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,...,Premium Tech Support_Yes,Streaming TV_Yes,Streaming Movies_Yes,Streaming Music_Yes,Unlimited Data_Yes,Contract_One Year,Contract_Two Year,Paperless Billing_Yes,Payment Method_Credit Card,Payment Method_Mailed Check
0,78,0,68701,0,1,0.00,8,39.65,39.65,0.00,...,False,False,True,False,False,False,False,True,False,False
1,74,1,55668,1,8,48.85,17,80.65,633.30,0.00,...,False,False,False,False,True,False,False,True,True,False
2,71,3,47534,0,18,11.33,52,95.45,1752.55,45.61,...,False,True,True,True,True,False,False,True,False,False
3,78,1,27778,1,25,19.76,12,98.50,2514.50,13.43,...,False,True,True,False,True,False,False,True,False,False
4,80,1,26265,1,37,6.33,14,76.50,2868.15,0.00,...,False,False,False,False,True,False,False,True,False,False

## Feature Scaling

Machine learning algorithms perform better when numerical features are on a similar scale. StandardScaler standardizes numerical variables by removing the mean and scaling to unit variance.

In [67]:
# =====================================================
# Identify Numerical Columns
# =====================================================

numeric_columns = X.select_dtypes(include=["int64", "float64"]).columns

print("Number of Numerical Features :", len(numeric_columns))

numeric_columns

Number of Numerical Features : 15

Index(['Age', 'Number of Dependents', 'Population', 'Number of Referrals',
       'Tenure in Months', 'Avg Monthly Long Distance Charges',
       'Avg Monthly GB Download', 'Monthly Charge', 'Total Charges',
       'Total Refunds', 'Total Extra Data Charges',
       'Total Long Distance Charges', 'Total Revenue', 'Satisfaction Score',
       'CLTV'],
      dtype='object')

In [68]:
# =====================================================
# Label Encoding Target Variable
# =====================================================

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y = label_encoder.fit_transform(y)

print("Label Encoding Completed")

print(np.unique(y))

Label Encoding Completed
[0 1]

In [69]:
# =====================================================
# Apply StandardScaler
# =====================================================

scaler = StandardScaler()

X[numeric_columns] = scaler.fit_transform(X[numeric_columns])

print("Standard Scaling Completed")

X.head()

Standard Scaling Completed

,Age,Number of Dependents,Population,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,...,Premium Tech Support_Yes,Streaming TV_Yes,Streaming Movies_Yes,Streaming Music_Yes,Unlimited Data_Yes,Contract_One Year,Contract_Two Year,Paperless Billing_Yes,Payment Method_Credit Card,Payment Method_Mailed Check
0,1.880110,-0.486835,2.201392,-0.650409,-1.278988,-1.486303,-0.612975,-0.834611,-0.988823,-0.248313,...,False,False,True,False,False,False,False,True,False,False
1,1.641292,0.551874,1.585200,-0.317185,-0.993743,1.676120,-0.172176,0.528063,-0.726848,-0.248313,...,False,False,False,False,True,False,False,True,True,False
2,1.462179,2.629292,1.200630,-0.650409,-0.586250,-0.752828,1.542040,1.019955,-0.232929,5.523605,...,False,True,True,True,True,False,False,True,False,False
3,1.880110,0.551874,0.266580,-0.317185,-0.301005,-0.207092,-0.417064,1.121324,0.103315,1.451245,...,False,True,True,False,True,False,False,True,False,False
4,1.999519,0.551874,0.195046,-0.317185,0.187986,-1.076516,-0.319109,0.390134,0.259379,-0.248313,...,False,False,False,False,True,False,False,True,False,False

# Feature Selection

At this stage, features with zero variance are removed because they do not contribute useful information for model training. The remaining features are retained for customer churn prediction.

In [70]:
# =====================================================
# Feature Selection
# Remove Zero Variance Features
# =====================================================

constant_columns = [
    col for col in X.columns
    if X[col].nunique() == 1
]

print("Constant Features Found:")
print(constant_columns)

X = X.drop(columns=constant_columns)

print()
print("Updated Feature Matrix Shape:")
print(X.shape)

Constant Features Found:
[]

Updated Feature Matrix Shape:
(7043, 43)

In [71]:
# =====================================================
# Feature Selection using VarianceThreshold
# =====================================================

from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0)

X_selected = selector.fit_transform(X)

selected_features = X.columns[selector.get_support()]

X = pd.DataFrame(X_selected, columns=selected_features)

print("Feature Selection Completed")
print()

print("Selected Features:", X.shape[1])
print("Feature Matrix Shape:", X.shape)

Feature Selection Completed

Selected Features: 43
Feature Matrix Shape: (7043, 43)

In [72]:
# =====================================================
# Final Feature Matrix
# =====================================================

print("Final Feature Matrix Shape")
print(X.shape)

print()

print("Target Distribution")
print(pd.Series(y).value_counts())

Final Feature Matrix Shape
(7043, 43)

Target Distribution
0    5174
1    1869
Name: count, dtype: int64

## Save Processed Dataset

The processed dataset is saved for model training in the next stage of the project.

In [73]:
# =====================================================
# Combine Features and Target
# =====================================================

processed_df = X.copy()

processed_df["Churn Label"] = y

processed_df.head()

,Age,Number of Dependents,Population,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,...,Streaming TV_Yes,Streaming Movies_Yes,Streaming Music_Yes,Unlimited Data_Yes,Contract_One Year,Contract_Two Year,Paperless Billing_Yes,Payment Method_Credit Card,Payment Method_Mailed Check,Churn Label
0,1.880110,-0.486835,2.201392,-0.650409,-1.278988,-1.486303,-0.612975,-0.834611,-0.988823,-0.248313,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
1,1.641292,0.551874,1.585200,-0.317185,-0.993743,1.676120,-0.172176,0.528063,-0.726848,-0.248313,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1
2,1.462179,2.629292,1.200630,-0.650409,-0.586250,-0.752828,1.542040,1.019955,-0.232929,5.523605,...,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1
3,1.880110,0.551874,0.266580,-0.317185,-0.301005,-0.207092,-0.417064,1.121324,0.103315,1.451245,...,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1
4,1.999519,0.551874,0.195046,-0.317185,0.187986,-1.076516,-0.319109,0.390134,0.259379,-0.248313,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1

In [74]:
# =====================================================
# Save Feature Engineered Dataset
# =====================================================

processed_df.to_csv(
    "../data/processed/feature_engineered_data.csv",
    index=False
)

print("Feature Engineered Dataset Saved Successfully")

Feature Engineered Dataset Saved Successfully

## Summary

Feature engineering has been completed successfully.

The following preprocessing steps were performed:

- Removed unnecessary identifier columns
- Separated features and target variable
- Applied One-Hot Encoding on categorical features
- Standardized numerical features using StandardScaler
- Created the final machine learning dataset
- Saved the processed dataset for model training