# Feature Engineering

## Objective

The objective of this notebook is to transform the cleaned telecom dataset into a machine learning ready dataset.

Tasks performed:

- Loading cleaned dataset
- Dropping unnecessary columns
- Separating target variable
- One-Hot Encoding
- Label Encoding (if required)
- Feature Scaling using StandardScaler
- Feature Selection
- Saving processed dataset

In [23]:
# =====================================================
# Import Required Libraries
# =====================================================

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

print("Libraries imported successfully.")

Libraries imported successfully.

In [24]:
# =====================================================
# Load Cleaned Dataset
# =====================================================

df = pd.read_csv("../data/processed/cleaned_telco_data.csv")

print("Dataset Loaded Successfully")
print()

df.head()

Dataset Loaded Successfully

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,...,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,California,...,20,0.00,59.65,3,Churned,Yes,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,California,...,0,390.80,1024.10,3,Churned,Yes,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,California,...,0,203.94,1910.88,2,Churned,Yes,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,California,...,0,494.00,2995.07,2,Churned,Yes,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,California,...,0,234.21,3102.36,2,Churned,Yes,67,2793,Price,Extra data charges

In [25]:
# =====================================================
# Dataset Shape and Columns
# =====================================================

print("Dataset Shape :", df.shape)

print("\nTarget Variable")

print(df["Churn Label"].value_counts())

Dataset Shape : (7043, 50)

Target Variable
Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

## Removing Unnecessary Columns

Some columns contain identifiers or information that should not be used during model training because they do not contribute to prediction or may cause data leakage.

In [26]:
# =====================================================
# Remove Identifier Columns
# =====================================================

drop_columns = [

    "Customer ID",
    "Country",
    "State",
    "City",
    "Zip Code",
    "Latitude",
    "Longitude",

    # Target Leakage Columns
    "Customer Status",
    "Churn Category",
    "Churn Reason",
    "Churn Score"

]
print("Columns Removed Successfully")

df.head()

Columns Removed Successfully

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,...,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,California,...,20,0.00,59.65,3,Churned,Yes,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,California,...,0,390.80,1024.10,3,Churned,Yes,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,California,...,0,203.94,1910.88,2,Churned,Yes,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,California,...,0,494.00,2995.07,2,Churned,Yes,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,California,...,0,234.21,3102.36,2,Churned,Yes,67,2793,Price,Extra data charges

## Separating Features and Target Variable

In [27]:
# =====================================================
# Separate Features and Target
# =====================================================

X = df.drop("Churn Label", axis=1)

y = df["Churn Label"]

print("Feature Matrix Shape :", X.shape)
print("Target Shape :", y.shape)

Feature Matrix Shape : (7043, 49)
Target Shape : (7043,)

## One-Hot Encoding

Categorical variables are converted into numerical format using One-Hot Encoding so that machine learning algorithms can process them.

In [28]:
# =====================================================
# One-Hot Encoding
# =====================================================

categorical_columns = X.select_dtypes(include="object").columns

print("Categorical Columns")

print(categorical_columns)

Categorical Columns
Index(['Customer ID', 'Gender', 'Under 30', 'Senior Citizen', 'Married',
       'Dependents', 'Country', 'State', 'City', 'Quarter',
       'Referred a Friend', 'Offer', 'Phone Service', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Online Security', 'Online Backup',
       'Device Protection Plan', 'Premium Tech Support', 'Streaming TV',
       'Streaming Movies', 'Streaming Music', 'Unlimited Data', 'Contract',
       'Paperless Billing', 'Payment Method', 'Customer Status',
       'Churn Category', 'Churn Reason'],
      dtype='object')

In [29]:
# =====================================================
# Apply One-Hot Encoding
# =====================================================

X = pd.get_dummies(
    X,
    columns=categorical_columns,
    drop_first=True
)

print("One-Hot Encoding Completed")
print()

print("New Feature Shape :", X.shape)

X.head()

One-Hot Encoding Completed

New Feature Shape : (7043, 8219)

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Population,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
0,78,0,90022,34.023810,-118.156582,68701,0,1,0.00,8,...,False,False,False,False,False,False,False,False,False,False
1,74,1,90063,34.044271,-118.185237,55668,1,8,48.85,17,...,False,False,False,False,False,False,False,False,False,False
2,71,3,90065,34.108833,-118.229715,47534,0,18,11.33,52,...,False,False,False,False,False,False,False,False,False,False
3,78,1,90303,33.936291,-118.332639,27778,1,25,19.76,12,...,False,True,False,False,False,False,False,False,False,False
4,80,1,90602,33.972119,-118.020188,26265,1,37,6.33,14,...,False,False,False,False,False,False,False,False,False,False

## Feature Scaling

Machine learning algorithms perform better when numerical features are on a similar scale. StandardScaler standardizes numerical variables by removing the mean and scaling to unit variance.

In [30]:
# =====================================================
# Identify Numerical Columns
# =====================================================

numeric_columns = X.select_dtypes(include=["int64", "float64"]).columns

print("Number of Numerical Features :", len(numeric_columns))

numeric_columns

Number of Numerical Features : 19

Index(['Age', 'Number of Dependents', 'Zip Code', 'Latitude', 'Longitude',
       'Population', 'Number of Referrals', 'Tenure in Months',
       'Avg Monthly Long Distance Charges', 'Avg Monthly GB Download',
       'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue', 'Satisfaction Score', 'Churn Score', 'CLTV'],
      dtype='object')

In [31]:
# =====================================================
# Label Encoding Target Variable
# =====================================================

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y = label_encoder.fit_transform(y)

print("Label Encoding Completed")

print(np.unique(y))

Label Encoding Completed
[0 1]

In [32]:
# =====================================================
# Apply StandardScaler
# =====================================================

scaler = StandardScaler()

X[numeric_columns] = scaler.fit_transform(X[numeric_columns])

print("Standard Scaling Completed")

X.head()

Standard Scaling Completed

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Population,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
0,1.880110,-0.486835,-1.865778,-0.880463,0.742757,2.201392,-0.650409,-1.278988,-1.486303,-0.612975,...,False,False,False,False,False,False,False,False,False,False
1,1.641292,0.551874,-1.843695,-0.872175,0.729456,1.585200,-0.317185,-0.993743,1.676120,-0.172176,...,False,False,False,False,False,False,False,False,False,False
2,1.462179,2.629292,-1.842618,-0.846023,0.708810,1.200630,-0.650409,-0.586250,-0.752828,1.542040,...,False,False,False,False,False,False,False,False,False,False
3,1.880110,0.551874,-1.714429,-0.915913,0.661033,0.266580,-0.317185,-0.301005,-0.207092,-0.417064,...,False,True,False,False,False,False,False,False,False,False
4,1.999519,0.551874,-1.553385,-0.901401,0.806071,0.195046,-0.317185,0.187986,-1.076516,-0.319109,...,False,False,False,False,False,False,False,False,False,False

# Feature Selection

At this stage, features with zero variance are removed because they do not contribute useful information for model training. The remaining features are retained for customer churn prediction.

In [33]:
# =====================================================
# Feature Selection
# Remove Zero Variance Features
# =====================================================

constant_columns = [
    col for col in X.columns
    if X[col].nunique() == 1
]

print("Constant Features Found:")
print(constant_columns)

X = X.drop(columns=constant_columns)

print()
print("Updated Feature Matrix Shape:")
print(X.shape)

Constant Features Found:
[]

Updated Feature Matrix Shape:
(7043, 8219)

In [39]:
# =====================================================
# Feature Selection using VarianceThreshold
# =====================================================

from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0)

X_selected = selector.fit_transform(X)

selected_features = X.columns[selector.get_support()]

X = pd.DataFrame(X_selected, columns=selected_features)

print("Feature Selection Completed")
print()

print("Selected Features:", X.shape[1])
print("Feature Matrix Shape:", X.shape)

Feature Selection Completed

Selected Features: 8219
Feature Matrix Shape: (7043, 8219)

In [40]:
# =====================================================
# Final Feature Matrix
# =====================================================

print("Final Feature Matrix Shape")
print(X.shape)

print()

print("Target Distribution")
print(pd.Series(y).value_counts())

Final Feature Matrix Shape
(7043, 8219)

Target Distribution
0    5174
1    1869
Name: count, dtype: int64

## Save Processed Dataset

The processed dataset is saved for model training in the next stage of the project.

In [41]:
# =====================================================
# Combine Features and Target
# =====================================================

processed_df = X.copy()

processed_df["Churn Label"] = y

processed_df.head()

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Population,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,...,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction,Churn Label
0,1.880110,-0.486835,-1.865778,-0.880463,0.742757,2.201392,-0.650409,-1.278988,-1.486303,-0.612975,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,1.641292,0.551874,-1.843695,-0.872175,0.729456,1.585200,-0.317185,-0.993743,1.676120,-0.172176,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,1.462179,2.629292,-1.842618,-0.846023,0.708810,1.200630,-0.650409,-0.586250,-0.752828,1.542040,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,1.880110,0.551874,-1.714429,-0.915913,0.661033,0.266580,-0.317185,-0.301005,-0.207092,-0.417064,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,1.999519,0.551874,-1.553385,-0.901401,0.806071,0.195046,-0.317185,0.187986,-1.076516,-0.319109,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [42]:
# =====================================================
# Save Feature Engineered Dataset
# =====================================================

processed_df.to_csv(
    "../data/processed/feature_engineered_data.csv",
    index=False
)

print("Feature Engineered Dataset Saved Successfully")

Feature Engineered Dataset Saved Successfully

## Summary

Feature engineering has been completed successfully.

The following preprocessing steps were performed:

- Removed unnecessary identifier columns
- Separated features and target variable
- Applied One-Hot Encoding on categorical features
- Standardized numerical features using StandardScaler
- Created the final machine learning dataset
- Saved the processed dataset for model training